//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 08-Feb-20 14:39:18 CST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type APITokens struct {
	UserID    uint32
	Token     string `sql:"primary_key"`
	CreatedAt time.Time
	UpdatedAt time.Time
}
