//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 08-Feb-20 15:43:50 CST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID        uint32 `sql:"primary_key"`
	Name      string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
