//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 08-Feb-20 15:43:50 CST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/mysql"
)

var APITokens = newAPITokensTable()

type APITokensTable struct {
	mysql.Table

	//Columns
	UserID    mysql.ColumnInteger
	Token     mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

// creates new APITokensTable with assigned alias
func (a *APITokensTable) AS(alias string) *APITokensTable {
	aliasTable := newAPITokensTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newAPITokensTable() *APITokensTable {
	var (
		UserIDColumn    = mysql.IntegerColumn("user_id")
		TokenColumn     = mysql.StringColumn("token")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
	)

	return &APITokensTable{
		Table: mysql.NewTable("listable", "api_tokens", UserIDColumn, TokenColumn, CreatedAtColumn, UpdatedAtColumn),

		//Columns
		UserID:    UserIDColumn,
		Token:     TokenColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     mysql.ColumnList{UserIDColumn, TokenColumn, CreatedAtColumn, UpdatedAtColumn},
		MutableColumns: mysql.ColumnList{UserIDColumn, CreatedAtColumn, UpdatedAtColumn},
	}
}
