//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 08-Feb-20 15:43:50 CST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/mysql"
)

var GroupsUsers = newGroupsUsersTable()

type GroupsUsersTable struct {
	mysql.Table

	//Columns
	UserID    mysql.ColumnInteger
	GroupID   mysql.ColumnInteger
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

// creates new GroupsUsersTable with assigned alias
func (a *GroupsUsersTable) AS(alias string) *GroupsUsersTable {
	aliasTable := newGroupsUsersTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newGroupsUsersTable() *GroupsUsersTable {
	var (
		UserIDColumn    = mysql.IntegerColumn("user_id")
		GroupIDColumn   = mysql.IntegerColumn("group_id")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
	)

	return &GroupsUsersTable{
		Table: mysql.NewTable("listable", "groups_users", UserIDColumn, GroupIDColumn, CreatedAtColumn, UpdatedAtColumn),

		//Columns
		UserID:    UserIDColumn,
		GroupID:   GroupIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     mysql.ColumnList{UserIDColumn, GroupIDColumn, CreatedAtColumn, UpdatedAtColumn},
		MutableColumns: mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn},
	}
}
